### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by abb1991** [shawnmjones3/prj-rev-bwfs-dasmoto#2]
I like your use of chained classes!

```
h1, h2, h3, p {
	font-family: Helvetica;
}
```

Your CSS looks good. I'd suggest styling elements directly so your don't have to access them through parent/child relationships. It'll make your code less likely to break if you add new HTML, or move different elements around.

**Comment by shawnmjones3** [comment]
Styling elements directly?  Could you give me a quick example of what you mean so I don't misinterpret?

**Comment by shawnmjones3** [comment]
Nevermind.  You explained it in the summary you left for me (and it is what I thought you were saying).  Thanks.
